# ===================================
# TestCentral - Docker Compose
# ===================================

version: "3.8"

services:
  # Main application service
  testcentral:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testcentral-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount logs directory
      - ./logs:/app/logs
    networks:
      - testcentral-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: testcentral-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - testcentral
    networks:
      - testcentral-network
    profiles:
      - with-nginx

  # Redis for caching (future implementation)
  redis:
    image: redis:7-alpine
    container_name: testcentral-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - testcentral-network
    profiles:
      - with-redis

  # PostgreSQL database (future implementation)
  postgres:
    image: postgres:15-alpine
    container_name: testcentral-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: testcentral
      POSTGRES_USER: testcentral
      POSTGRES_PASSWORD: testcentral_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - testcentral-network
    profiles:
      - with-database

networks:
  testcentral-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
# ===================================
# Usage Examples:
#
# Basic deployment:
# docker-compose up -d
#
# With Nginx proxy:
# docker-compose --profile with-nginx up -d
#
# Full stack with database:
# docker-compose --profile with-nginx --profile with-redis --profile with-database up -d
#
# Development with logs:
# docker-compose up
#
# Rebuild and start:
# docker-compose up --build
#
# Stop all services:
# docker-compose down
#
# Remove volumes (careful!):
# docker-compose down -v
# ===================================
